"""Build a reversible --main-pack launcher. The installed Steam files stay untouched."""
import hashlib
import json
from pathlib import Path
from native import GAME, ROOT, gdre
from pck import build_archive, project_entries, read_entry, encode_project, variant
from build_worker import build, OUTPUT, RULES, replace_function
import re

def main():
    build()
    source = GAME / 'BackpackBattles.pck'
    target = OUTPUT.parent
    settings = project_entries(read_entry(source, 'res://project.binary'))
    settings['autoload/BackpackLab'] = variant('*res://BackpackLab/Adapter.gd')
    replacements = {'res://project.binary': encode_project(settings)}
    # Observe completed native save/restore operations without intercepting keys.
    undo = (RULES / 'decompiled/Utility__UndoStack.gd').read_text(encoding='utf-8')
    undo = undo.replace('signal state_changed', 'signal lab_layout_saved(slot)\nsignal lab_layout_restored(slot)\nsignal state_changed', 1)
    for method, signal in [('makeManualSnapshot', 'lab_layout_saved'), ('restoreSnapshop', 'lab_layout_restored')]:
        match = re.search(rf'(?m)^func {method}\([^\n]*\n(?:[\t ].*\n|\n)*', undo)
        body = match.group().split('\n', 1)[1].rstrip() + f'\n\temit_signal("{signal}", index)\n'
        undo = replace_function(undo, method, body)
    undo += '\nfunc lab_capture_snapshot():\n\treturn InventoryState.new()\n'
    patched = ROOT / 'data/local_runtime/adapter-build' 
    patched.mkdir(parents=True, exist_ok=True)
    (patched / 'UndoStack.gd').write_text(undo, encoding='utf-8')
    gdre(['--compile=' + str(patched / 'UndoStack.gd'), '--bytecode=3.6', '--output=' + str(patched)])
    replacements['res://BackpackLab/UndoStack.gdc'] = (patched / 'UndoStack.gdc').read_bytes()
    replacements['res://Utility/UndoStack.gd.remap'] = b'[remap]\npath="res://BackpackLab/UndoStack.gdc"\n'
    for path in (ROOT / 'plugin/godot').glob('*.gd'):
        if path.name != 'Worker.gd':
            replacements['res://BackpackLab/' + path.name] = path.read_bytes()
    replacements['res://BackpackLab/rules.json'] = read_entry(OUTPUT / 'BackpackLabWorker.pck', 'res://BackpackLab/rules.json')
    replacements['res://BackpackLab/precision.json'] = (ROOT / 'plugin/precision.json').read_bytes()
    build_archive(source, target / 'BackpackLab.pck', replacements)
    hashes = {name: hashlib.sha256((GAME / name).read_bytes()).hexdigest() for name in
              ('BackpackBattles.exe', 'BackpackBattles.pck', 'steam_api64.dll', 'libgdsqlite.dll')}
    worker_hashes = {name: hashlib.sha256((OUTPUT / name).read_bytes()).hexdigest() for name in
                     ('BackpackLabWorker.exe', 'BackpackLabWorker.pck', 'steam_api64.dll', 'libgdsqlite.dll')}
    (target / 'installed-source.json').write_text(json.dumps({'game_directory': str(GAME), 'hashes': hashes,
        'worker_hashes': worker_hashes, 'plugin_sha256': hashlib.sha256((target / 'BackpackLab.pck').read_bytes()).hexdigest()}, indent=2), encoding='utf-8')
    import sys
    if not getattr(sys, 'frozen', False):
        from build_windows import compile_launcher
        compile_launcher(target / 'BackpackLab.exe')
    # Remove only the legacy entrypoints generated by this builder.
    for legacy in ('Launch-BackpackLab.ps1', '启动背包实验室.cmd'):
        (target / legacy).unlink(missing_ok=True)
    print('Plugin and launcher built:', target)

if __name__ == '__main__':
    main()
